export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FOLLOWUP_CALL_COUNT_SUCCESS = 'FOLLOWUP_CALL_COUNT_SUCCESS';
export const GROUP_NAME_SUCCESS = 'GROUP_NAME_SUCCESS';

export const GROUP_TOUR_COMPLETION_COUNT_SUCCESS = 'GROUP_TOUR_COMPLETION_COUNT_SUCCESS';

export const SET_PERMISSIONS = 'SET_PERMISSIONS';

export const GT_FAMILY_HEAD_DATA_STATUS_SUCCESS = 'GT_FAMILY_HEAD_DATA_STATUS_SUCCESS';
export const GT_ADVANCE_PAY_SUCCESS = 'GT_ADVANCE_PAY_SUCCESS';

export const CT_PACKAGE_FINALIZED_SUCCESS = 'CT_PACKAGE_FINALIZED_SUCCESS';

